---
- name: original playbook
  hosts: slave
  remote_user: root
  gather_facts: False
  ignore_errors: True

  tasks: 
  - name: disable selinux
    lineinfile: 
      regexp: '^SELINUX=enforcing'
      line: 'SELINUX=disabled'
      path: /etc/selinux/config
      backrefs: yes

  - name: disable firewall
    service: name=firewalld state=stopped

  - name: install rpm
    yum: name=https://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm state=present

  - name: yum makecache
    yum: name=* update_cache=yes

  - name: install agent
    yum: name=zabbix-agent state=latest

  - name: install agent-get
    yum: name=zabbix-get state=latest

  - name: install agent-sender
    yum: name=zabbix-sender state=latest

  - name: cgcf1
    lineinfile: 
      backrefs: yes 
      path: /etc/zabbix/zabbix_agentd.conf 
      regexp: '^Server=127.0.0.1' 
      line: 'Server=172.16.102.17' 

  - name: cgcf2
    lineinfile: 
      backrefs: yes
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^ServerActive=127.0.0.1'
      line: 'ServerActive=172.16.102.17'

  - name: start
    service: name=zabbix-agent enabled=yes state=restarted
